python amc_search_vgg.py \
    --job=train \
    --suffix=amc_vgg16_60 \
    --model=vgg16 \
    --dataset=cifar10 \
    --preserve_ratio=0.6 \
    --lbound=0.2 \
    --rbound=1 \
    --reward=acc_reward \
    --data_root=/home/dataset/cifar \
    --ckpt_path=/home/young/liuyixin/vgg16_demo/checkpoints/vgg16_cifar10.pt \
    --seed=2020 \
    --rmsize=200 \
    --bsize=64 